import vazirFont from '@/constants/localFonts'
import './globals.css'
import Header from './Header'
import { Toaster } from 'react-hot-toast'
import Providers from './Providers'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<body
				suppressHydrationWarning={true}
				className={`${vazirFont.variable} font-sans`}
			>
				<Providers>
					<Toaster />
					<Header />
					<div className="container xl:max-w-screen-xl">
						{children}
					</div>
				</Providers>
			</body>
		</html>
	)
}
